package com.illumina.desktop;


import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Collections;
import java.util.EventObject;
import java.util.List;

import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JPanel;


/**
 * Default extension of BusyDialog that displays an animated gif
 * @author  bking
 */
public class BusyDialog  extends JDialog
{
    protected List<BusyDialogCancelListener> listeners;
    
    public BusyDialog(java.awt.Frame parent)
    {
        super(parent);
        initComponents();
    }

    public BusyDialog()
    {
        super();
        initComponents();
    }    
    
    
    public void receiveProgress(String message)
    {
        lblProgressMessage.setText(message);
    }
    
    

    public void setCancelable(boolean cancelable)
    {
        northPanel.setVisible(cancelable);
    }
    
    protected void fireBusyDialogCancelEvent(EventObject e)
    {
        if (listeners != null)
        {
            for(BusyDialogCancelListener l:listeners)
            {
                l.onCancel(e);
            }
        }
    }
    
    public void addBusyDialogCancelListener(BusyDialogCancelListener l)
    {
        if (listeners == null)listeners =  Collections.synchronizedList(new ArrayList<BusyDialogCancelListener>());
        if (!listeners.contains(l))listeners.add(l);
    }
    
    public void removeBusyDialogCancelListener(BusyDialogCancelListener l)
    {
        if (listeners != null && listeners.contains(l))listeners.remove(l);
    } 

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents()
    {
        mainPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        centerPanel = new javax.swing.JPanel();
        lblBanner = new javax.swing.JLabel();
        lblAnimation = new javax.swing.JLabel();
        southPanel = new javax.swing.JPanel();
        lblProgressMessage = new javax.swing.JLabel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        
        getContentPane().add(mainPanel, BorderLayout.CENTER);
        mainPanel.setBorder(BorderFactory.createEmptyBorder(0, 3, 1, 3));
        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        
        centerPanel.setLayout(new java.awt.BorderLayout());
        
        lblBanner.setBackground(new java.awt.Color(255, 255, 255));
        lblBanner.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBanner.setIcon(ImageProvider.instance().getIcon("illumina_banner.png"));
        lblBanner.setOpaque(true);
        lblBanner.setPreferredSize(new java.awt.Dimension(200, 75));
        centerPanel.add(lblBanner, java.awt.BorderLayout.CENTER);
        
        lblAnimation.setBackground(new java.awt.Color(255, 255, 255));
        lblAnimation.setIcon(ImageProvider.instance().getIcon("wait_animation.gif"));
        lblAnimation.setOpaque(true);
        centerPanel.add(lblAnimation, java.awt.BorderLayout.LINE_START);
        
        mainPanel.add(centerPanel, java.awt.BorderLayout.CENTER);
        
        southPanel.setLayout(new java.awt.BorderLayout());
        
        lblProgressMessage.setBackground(new java.awt.Color(255, 255, 255));
        lblProgressMessage.setOpaque(true);
        lblProgressMessage.setText("");
        southPanel.add(lblProgressMessage, java.awt.BorderLayout.NORTH);
        
        mainPanel.add(southPanel, java.awt.BorderLayout.SOUTH);
        
        northPanel = new JPanel();
        northPanel.setBackground(Color.WHITE);
        FlowLayout flowLayout = (FlowLayout) northPanel.getLayout();
        flowLayout.setAlignment(FlowLayout.RIGHT);
        mainPanel.add(northPanel, BorderLayout.NORTH);
        
        btnCancel = new JButton();
        btnCancel.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) 
            {
                fireBusyDialogCancelEvent(new EventObject(this));
            }
        });
        btnCancel.setIcon(ImageProvider.instance().getIcon("cancel.png"));

        northPanel.add(btnCancel);
        
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel centerPanel;
    protected javax.swing.JPanel mainPanel;
    protected javax.swing.JPanel southPanel;
    protected javax.swing.JLabel lblAnimation;
    protected javax.swing.JLabel lblBanner;
    protected javax.swing.JLabel lblProgressMessage;
    private JPanel northPanel;
    private JButton btnCancel;
    // End of variables declaration//GEN-END:variables
    
}
